### PR TITLE
Make mod multiplayer compatible.

### PR DESCRIPTION
**Pull request by YPetremann**

### CODE REVIEW

**Comment by narc0tiq** [comment]
Nice, thank you. I'll post this up to Jeroon's thread as v0.5.6 as soon as I've tested it a bit.

**Comment by narc0tiq** [comment]
Something to note: you can't do this if you're playing on a headless server; at a guess, this is because the headless peer doesn't really have rendering capabilities. I got a very confusing warning, too:

`107.508 Warning LuaGameScript.cpp:1078: luaremove_path error: Scripts can only use file space inside of /home/narc/srv/factorio/script-output (requested path was /home/narc/srv/factorio/script-output/FactorioMaps/bob-world-3)`

...but the crash immediately thereafter suggests it just can't happen:

```
#0  0x7fbc88f2cd40 in ?? at ??:0
#1  0x5e1f8a in getWidth at /tmp/factorio-yavVX5/src/Graphics/Display.cpp:197
#2  0x4455ff in luaTakeScreenshot at /tmp/factorio-yavVX5/src/Script/LuaGameScript.cpp:990
#3  0xa8169e in callWrapper at /tmp/factorio-yavVX5/src/Script/LuaBinder.hpp:307
[...remainder ellided...]
```

I don't consider this to be a blocking issue, and I'd rather have _some_ multiplayer compatibility than none, but it's just something to be aware of.

**Comment by narc0tiq** [comment]
And it's posted: http://www.factorioforums.com/forum/viewtopic.php?p=107063#p107063

**Comment by YPetremann** [comment]
The basic idea is not really to use it with multiples players, but player are indexed and so all player can save the map, install the mod, load the game in single and make a render of the map, whenever their index is 1, 3 or 134 ...

**Comment by narc0tiq** [comment]
Yes, that's why I took the patch. Thank you again for taking the time to write it.

**Pull request merged**
